baseURL = "https://privacytoronto.github.io/"
languageCode = "en-us"
title = "Privacy Discussions in Toronto"
theme = "crab"

[params]
description = "Let's learn about privacy together!"

[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 3
name = "Events"
url = "/blog/"

[[menu.main]]
weight = 4
name = "Resources"
url = "/resources/"

[[menu.main]]
weight = 5
name = "Code Of Conduct"
url = "/codeofconduct/"


[[menu.main]]
weight = 6
name = "About"
url = "/about/"


